data_path: "../data"
llm_url: "http://localhost:11434"
llm_name: "deepseek-r1:1.5b"
#embedding_model: "BAAI/bge-small-en"
embedding_model: "intfloat/multilingual-e5-large"
qdrant_url: "http://localhost:6333"
collection_name: "tfm-1"
chunk_size: 1024
#chunk_overlap: 1