data_path: "../data"
llm_url: "http://localhost:11434"
qdrant_url: "http://localhost:6333"
#embedding_model: "snowflake/snowflake-arctic-embed-l"
#embedding_model: "BAAI/bge-large-en-v1.5"
embedding_model: "BAAI/bge-small-en-v1.5"
#embedding_model: "nomic-ai/nomic-embed-text-v1.5-Q"
#embedding_model: "jinaai/jina-embeddings-v2-small-en"


#embedding_model: "intfloat/multilingual-e5-large"